spring:
  profiles:
    include: database # 서버 실행 환경과 테스트 환경을 분리 하기 위하여 설정을 분리
  devtools:
    restart:
      enabled: false
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            store_data_at_delete: true
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
